import React from "react";

// Example lists of top stocks and cryptos

const topStocks = [
    "NVIDIA Corporation: NVDA",
    "Apple Inc.: AAPL",
    "Alphabet (Google): GOOG",
    "Microsoft Corporation: MSFT",
    "Amazon.com, Inc.: AMZN",
    "Broadcom Inc.: AVGO",
    "Meta Platforms, Inc.: META",
    "Saudi Aramco: 2222.SR",
    "TSMC (Taiwan Semiconductor Manufacturing): TSM",
    "Tesla, Inc.: TSLA",
    "Berkshire Hathaway Inc.: BRK-B",
    "Eli Lilly and Company: LLY",
    "Walmart Inc.: WMT",
    "JPMorgan Chase & Co.: JPM",
    "Tencent Holdings Ltd: TCEHY",
    "Visa Inc.: V",
    "Oracle Corporation: ORCL",
    "Johnson & Johnson: JNJ",
    "Mastercard Incorporated: MA",
    "Exxon Mobil Corporation: XOM",
    "Samsung Electronics Co., Ltd.: 005930.KS",
    "Netflix, Inc.: NFLX",
    "ASML Holding NV: ASML",
    "Costco Wholesale Corporation: COST",
    "AbbVie Inc.: ABBV",
    "Palantir Technologies Inc.: PLTR",
    "Agricultural Bank of China: 601288.SS",
    "Bank of America Corporation: BAC",
    "Alibaba Group Holding Limited: BABA",
    "ICBC (Industrial and Commercial Bank of China): 1398.HK",
    "LVMH Moët Hennessy Louis Vuitton SE: MC.PA",
    "China Construction Bank: 601939.SS",
    "Home Depot (The): HD",
    "Advanced Micro Devices, Inc.: AMD",
    "Procter & Gamble Co.: PG",
    "General Electric: GE",
    "Coca-Cola Company (The): KO",
    "Roche Holding AG: ROG.SW",
    "Chevron Corporation: CVX",
    "Cisco Systems, Inc.: CSCO",
    "UnitedHealth Group Incorporated: UNH",
    "IBM (International Business Machines): IBM",
    "AstraZeneca PLC: AZN",
    "SAP SE: SAP",
    "Bank of China: 601988.SS",
    "Prosus N.V.: PRX.AS",
    "Wells Fargo & Company: WFC",
    "PetroChina Company Limited: 0857.HK",
    "Morgan Stanley: MS",
    "Caterpillar Inc.: CAT",
    "Micron Technology, Inc.: MU",
    "Toyota Motor Corporation: TM",
    "Merck & Co., Inc.: MRK",
    "Kweichow Moutai Co., Ltd.: 600519.SS",
    "Nestlé S.A.: NESN.SW",
    "Hermès International: RMS.PA",
    "American Express Company: AXP",
    "Novartis AG: NVS",
    "Goldman Sachs Group, Inc. (The): GS",
    "SK Hynix Inc.: 000660.KS",
    "Philip Morris International Inc.: PM",
    "T-Mobile US, Inc.: TMUS",
    "RTX Corporation: RTX",
    "Abbott Laboratories: ABT",
    "McDonald's Corporation: MCD",
    "Thermo Fisher Scientific Inc.: TMO",
    "Salesforce, Inc.: CRM",
    "Intuitive Surgical, Inc.: ISRG",
    "PepsiCo, Inc.: PEP",
    "AppLovin Corporation: APP",
    "Applied Materials, Inc.: AMAT",
    "Lam Research Corporation: LRCX",
    "Intel Corporation: INTC",
    "Linde plc: LIN",
    "Citigroup Inc.: C",
    "Walt Disney Company (The): DIS",
    "Amgen Inc.: AMGN",
    "AT&T Inc.: T",
    "Uber Technologies, Inc.: UBER",
    "QUALCOMM Incorporated: QCOM",
    "NextEra Energy, Inc.: NEE",
    "Blackstone Inc.: BX",
    "Intuit Inc.: INTU",
    "Verizon Communications Inc.: VZ",
    "Amphenol Corporation: APH",
    "TJX Companies, Inc. (The): TJX",
    "ServiceNow, Inc.: NOW",
    "Charles Schwab Corporation (The): SCHW",
    "Arista Networks, Inc.: ANET",
    "GE Vernova: GEV",
    "BlackRock, Inc.: BLK",
    "Danaher Corporation: DHR",
    "Mondelez International, Inc.: MDLZ",
    "Duke Energy Corporation: DUK",
    "Conocophillips: COP",
    "Deere & Company: DE",
    "Waste Management, Inc.: WM",
    "Palo Alto Networks, Inc.: PANW",
    "S&P Global Inc.: SPGI",
    "Lockheed Martin Corporation: LMT",
    "Analog Devices, Inc.: ADI"
];

const topCryptos = [
    "Bitcoin: BTC",
    "Ethereum: ETH",
    "Tether USDt: USDT",
    "XRP: XRP",
    "BNB: BNB",
    "Solana: SOL",
    "USD Coin: USDC",
    "TRON: TRX",
    "Dogecoin: DOGE",
    "Cardano: ADA",
    "Bitcoin Cash: BCH",
    "Wrapped Bitcoin: WBTC",
    "Chainlink: LINK",
    "Monero: XMR",
    "Stellar: XLM",
    "USDS: USDS",
    "Ethena USDe: USDE",
    "Litecoin: LTC",
    "Zcash: ZEC",
    "Hedera: HBAR",
    "Avalanche: AVAX",
    "Sui: SUI",
    "Dai: DAI",
    "Shiba Inu: SHIB",
    "Toncoin: TON",
    "Cronos: CRO",
    "Uniswap: UNI",
    "PayPal USD: PYUSD",
    "Polkadot: DOT",
    "Mantle: MNT",
    "Bittensor: TAO",
    "Aave: AAVE",
    "NEAR Protocol: NEAR",
    "Ethereum Classic: ETC",
    "Internet Computer: ICP",
    "Ethena: ENA",
    "Pepe: PEPE",
    "Ondo: ONDO",
    "Kaspa: KAS",
    "Worldcoin: WLD",
    "Aptos: APT",
    "Polygon: POL",
    "PAX Gold: PAXG",
    "Algorand: ALGO",
    "Arbitrum: ARB",
    "Cosmos: ATOM",
    "Filecoin: FIL",
    "The Sandbox: SAND",
    "ImmutableX: IMX",
    "RenderToken: RNDR",
    "Injective: INJ",
    "Fantom: FTM",
    "Axie Infinity: AXS",
    "Theta Network: THETA",
    "Decentraland: MANA",
    "The Graph: GRT",
    "EOS: EOS",
    "IOTA: IOTA",
    "VeChain: VET",
    "Sui: SUI",
    "SingularityNET: AGIX",
    "Conflux: CFX",
    "Flow: FLOW",
    "Mina: MINA",
    "Gala: GALA",
    "Klaytn: KLAY",
    "Zilliqa: ZIL",
    "Tezos: XTZ",
    "Aptos: APT",
    "THORChain: RUNE",
    "Dash: DASH",
    "Curve DAO Token: CRV",
    "dYdX: DYDX",
    "Loopring: LRC",
    "Synthetix: SNX",
    "Compound: COMP",
    "Maker: MKR",
    "Rocket Pool: RPL",
    "Frax Share: FXS",
    "GMX: GMX",
    "Band Protocol: BAND",
    "Ocean Protocol: OCEAN",
    "Fetch.ai: FET",
    "Aelf: ELF",
    "WOO Network: WOO",
    "Celo: Celo",
    "PancakeSwap: CAKE",
    "Basic Attention Token: BAT",
    "Mask Network: MASK",
    "Terra Classic: LUNC",
    "JUST: JST",
    "Tellor: TRB",
    "Nexo: NEXO",
    "Qtum: QTUM",
    "Reserve Rights: RSR",
    "Alchemy Pay: ACH",
    "Metis: METIS",
    "Arweave: AR",
    "SushiSwap: SUSHI",
    "Balancer: BAL",
    "Acala: ACA",
    "Celer Network: CELR"
];

export default function TopMarkets() {
    return (
        <div style={{ padding: "20px" }}>
            <h1>Top Markets</h1>
            <div
                style={{
                    display: "flex",
                    gap: "40px",
                    flexWrap: "wrap"
                }}
            >
                {/* Stocks Column */}
                <div style={{ flex: "1 1 300px" }}>
                    <h2>Top Stocks</h2>
                    <ul>
                        {topStocks.map((stock, idx) => (
                            <li key={idx}>{stock}</li>
                        ))}
                    </ul>
                </div>

                {/* Cryptos Column */}
                <div style={{ flex: "1 1 300px" }}>
                    <h2>Top Cryptos</h2>
                    <ul>
                        {topCryptos.map((crypto, idx) => (
                            <li key={idx}>{crypto}</li>
                        ))}
                    </ul>
                </div>
            </div>
        </div>
    );
}
